name: Invicti Source Scan
on:
  push:
    branches: [main]
jobs:
  invicti-source-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Invicti Source Scan
        env:
          INVICTI_API_TOKEN: ${{ secrets.INVICTI_API_TOKEN }}
        run: |
          mkdir -p "${{ github.workspace }}/output"
          chmod a+rwx "${{ github.workspace }}/output"
          docker run --rm \
            -v "${{ github.workspace }}":/code:ro \
            -v "${{ github.workspace }}/output":/output \
            -e SCANNER_SERVICE_NAME="${{ github.event.repository.name }}" \
            -e INVICTI_SYNC=true \
            -e INVICTI_API_TOKEN \
            -e INVICTI_NAD_CONFIG_ID="9b31a503-7d74-4e07-be8b-dd4479a24cd7" \
            -e INVICTI_NAD_URL="https://platform.invicti.com/api/apihub/v1/nad" \
            registry.invicti.com/invicti-platform/invicti-source-scan:latest
